### PR TITLE
server page

### PR DESCRIPTION
**Pull request by Sanzouille**
Created server list page

### CODE REVIEW

**Comment by ScalaWilliam** [comment]
Should modify template.html as well to add a link to this.
Now I can see it as: http://alfa.actionfps.com/questions/servers/

Don't you want just /servers/ ?

**Comment by ScalaWilliam** [comment]
Refer to issue when making a PR: #12

**Comment by lucasgautheron** [comment]
There was already a link pointing to /questions/servers in the "question" page, hence the current location. 

https://github.com/ScalaWilliam/ActionFPS/pull/23#issuecomment-161191431

**Comment by ScalaWilliam** [comment]
I'd add a link to the main navigation. It'll be a bit wide, so I suggest you shorten the Gitter and GitHub bits.

**Pull request closed without merging**
