### PR TITLE
Project structure

### LINKED ISSUE #431: Integrate SBT project structure diagram producer into the project
Skills required: SBT, Scala

At the moment I'm using this funky hack with [JetBrains sbt-structure](https://github.com/JetBrains/sbt-structure) and some XSLT (Saxon) here:
https://github.com/ActionFPS/dev-doc/blob/master/Makefile

This requires a graphviz, sbt and coursier installation. Usage is: `sbt SBT_REPO=/path/to/ActionFPS`.

What I'm looking instead to do is to self-contain it and have something that could automatically generate it from inside the project itself.

I'd like a root project SBT task definition within this project called `generateXmlStructure` and `generateDotStructure`. I intend to use the XML structure at some point.

**Purpose: Documentation. The Dot structure I use to generate a nice looking graph with URLs to the GitHub source code, as per demonstration here: https://actionfps.github.io/dev-doc/structure.svg**

Demo:
screen shot 2017-10-29 at 08 47 09

There's https://github.com/jrudolph/sbt-dependency-graph but it seems to generate something rather different from what I want, eg per-project full dependencies, creating multiple files.

I'll pay US$25 for the completion of this task via [ScalaWilliam Work](http://work.scalawilliam.com/). As per the [rules](http://work.scalawilliam.com/rules/), type "**I agree to the [rules](http://work.scalawilliam.com/rules/) and am taking on this task**" to lock this task to yourself.

Work item is here: http://work.scalawilliam.com/integrate-sbt-project-diagram/

### PR DESCRIPTION
**Pull request by laughedelic**
Fixes #431.

### Task

> What I'm looking instead to do is to self-contain it and have something that could automatically generate it from inside the project itself.

This is a straightforward reimplementation of the referenced Makefile code as a pair of sbt tasks. Dependencies are handled by sbt, so it's self-contained.

> I'd like a root project SBT task definition within this project called `generateXmlStructure` and `generateDotStructure`. I intend to use the XML structure at some point.

I added these two tasks. Each of them returns the `File` that it generated.

### Usage

Just call `generateXmlStructure` or `generateDotStructure` from the sbt shell. The latter depends on the former, so you can just call `generateDotStructure` and both files will be generated:
- `target/structure.xml`
- `target/structure.dot`

### Notes

As indicated in the rules, I tried to keep it simple. So some things could be improved:
- XML output file is set through the `sbtStructureOutputFile` setting, there could be a separate setting for this file if needed (as well as for the DOT output file).
- `struct.xml` file is added in the root of the project and its location is hardcoded. There could be a setting for it.

### CODE REVIEW

**Comment by laughedelic** [comment]
By the way, if you're interested in generating SVG, I can add it too (no need to have graphviz installed).

**Comment by ScalaWilliam** [comment]
Sure. I missed the [`target/structure.svg` task](https://github.com/ActionFPS/dev-doc/blob/master/Makefile#L29).

**Comment by laughedelic** [comment]
Done.

**Comment by ScalaWilliam** [comment]
Sent you e-mail.

**Pull request merged**
