### PR TITLE
Download page presentation

### LINKED ISSUE #115: Download button in menu
And on page big red button. Version,  Windows icon. No need for changelog.

Maybe install instructions. Or video. Or screen shot. "How to get started"

### PR DESCRIPTION
**Pull request by lucasgautheron**
#115
What do you think ?
CSS stuff not my cup of tea, but the idea is here.

### CODE REVIEW

**Comment by lucasgautheron** [comment]
downloadpage

**Comment by lucasgautheron** [comment]
NB: i have no idea if the linux binaries actually work on redhat systems.

**Comment by ScalaWilliam** [comment]
"Debian based" = just say "Ubuntu or Debian", "Redhat based" = "Fedora or Redhat"?

Once that's done it's good to merge

**Comment by lucasgautheron** [comment]
I think maybe @Paul255 wanted to tweak it a bit (e.g. slight color change), otherwise it should be ready for merge.

**Comment by ScalaWilliam** [comment]
:+1:

**Pull request merged**
