### PR TITLE
Improved signatures layout

### LINKED ISSUE #193: Improve the signature quality
It looks really ugly right now:
https://actionfps.com/player/signature.svg?id=hakou

Let's get them looking better, K? Fonts, colours, spacing, layout, design, etc.

* https://github.com/ScalaWilliam/ActionFPS/blob/master/web/app/views/player/Signature.scala
* https://github.com/ScalaWilliam/ActionFPS/blob/master/web/dist/www/sig-template.svg

The SVG template is editable with Inkscape. Most important thing is to keep the IDs consistent, that's all.

### PR DESCRIPTION
**Pull request by lucasgautheron**
Based on hi-skill signatures and DaylixX's work.
Fixes #193

### CODE REVIEW

**Comment by lucasgautheron** [comment]
Maybe add more data ? And also icons for some achievements such as butcher ?

**Comment by ScalaWilliam** [comment]
Do that in a separate PR.

**Comment by ScalaWilliam** [comment]
screen shot 2017-01-08 at 20 49 07
incorrect/missing/uncommon font?

**Comment by lucasgautheron** [comment]
Oh yes, didn't realize @DaylixX used a special font.

**Comment by ScalaWilliam** [comment]
might be able to use a more standard font though. Lighter = always better :D

**Comment by lucasgautheron** [comment]
Doesn't fix the positioning issue apparently. Firefox and inkscape behave the same. Chrome behaves otherwise. Chrome's behavior seems more consistent (the values of x/y required for a good fit are compatible with the viewport parameters in Chrome)

**Comment by ScalaWilliam** [comment]
Could be due to alignment, some text perhaps should be `text-align: right` but isn't?

**Comment by lucasgautheron** [comment]
signature

**Comment by ScalaWilliam** [comment]
LGTM 👍 

I'd suggest to add text shadow (can do that in a separate PR) to add a bit more contract.

**Comment by ScalaWilliam** [comment]
Poor contrast eg here:

screen shot 2017-01-10 at 07 54 44

**Comment by ScalaWilliam** [comment]
#233

**Pull request merged**
