### PR TITLE
Improved signature contrast

### LINKED ISSUE #233: Add contrast to signature
Poor contrast eg here:

screen shot 2017-01-10 at 07 54 44

### PR DESCRIPTION
**Pull request by lucasgautheron**
Fixes #233

### CODE REVIEW

**Comment by lucasgautheron** [comment]
sig

**Comment by lucasgautheron** [comment]
@ScalaWilliam @Paul255 if there's no protest today I'll merge

**Comment by ScalaWilliam** [comment]
Try 0.6-0.7-0.8 stroke, merge after :) It's a bit too bold

And close corresponding ticket.

**Comment by Paul255** [comment]
There might be a problem when the player doesn't have any favorite map :

https://actionfps.com/player/signature.svg?id=underarm
https://actionfps.com/player/signature.svg?id=kaz

**Comment by lucasgautheron** [comment]
That's a separate problem, create an issue

**Pull request merged**
