### PR TITLE
An idea for screenshots.html

### PR DESCRIPTION
**Pull request by DnC-f0r3v3r**
A commit for creating screenshots.html. Incomplete?

## Tasks to completion
1. [x] Add a link in template.html to /screenshots/ with title 'Screenshots' so that people can navigate to the page.
2. [x] Update the <img src value to link to a smaller version of screenshot (maybe 480px in width). This is to make it easier to browse the screenshots and load faster. Try to use PNG for the thumbnail for higher quality.
3. [x] Host the screenshots on GitHub. Just paste them here in an issue comment box, and then it gives you an <img you can use. This will ensure that images are permanently hosted in reliable infrastructure (imgur may remove images at any time)

### CODE REVIEW

**Comment by DnC-f0r3v3r** [comment]
I am not sure what kind of styling this needs, I was only trying to contribute based on the comment in AFPS announcements. If you can give me some feedback, I can make it better suited.

**Comment by ScalaWilliam** [comment]
Thanks for this, here are the things needed to complete this:

1. Add a link in template.html to /screenshots/ with title 'Screenshots' so that people can navigate to the page.
2. Update the <img src value to link to a smaller version of screenshot (maybe 480px in width). This is to make it easier to browse the screenshots and load faster. Try to use PNG for the thumbnail for higher quality.
3. Host the screenshots on GitHub. Just paste them here in an issue comment box, and then it gives you an <img you can use. This will ensure that images are permanently hosted in reliable infrastructure (imgur may remove images at any time)
4. In https://github.com/ScalaWilliam/ActionFPS/blob/master/web/app/controllers/MiscController.scala add a line  ` def screenshots = renderStatic("screenshots.html")`. This is to pass screenshots.html to render the page.
5. In https://github.com/ScalaWilliam/ActionFPS/blob/master/web/conf/routes add a line  `GET         /screenshots/                               @controllers.MiscController.screenshots`. This links the route to the controller action.

**Comment by ScalaWilliam** [comment]
I updated your first comment to include a check list to help with this.

**Comment by ScalaWilliam** [comment]
This is for ticket #185

**Comment by ScalaWilliam** [comment]
Removed the last two instructions due to 40ac5a35f449c356f15b5aedbed86d5d4e7bda39

In the file you just need to specify the target URL you want it to render at, such as here:
https://github.com/ScalaWilliam/ActionFPS/commit/40ac5a35f449c356f15b5aedbed86d5d4e7bda39#diff-3a224469c4be9bd0a4ada22451e59b27R1

**Comment by ScalaWilliam** [comment]
screen shot 2016-12-30 at 05 01 15

I did `sbt web/run` and then went to http://localhost:9000/screenshots/
Only one last comment, the text is not very readable. To fix that, 
* [ ] Add `id="articles"` to the article and I'll merge.

**Comment by ScalaWilliam** [comment]
Nice work so far 👍

**Pull request merged**
