### PR TITLE
Live game spectate teams display fix ( #48 )

### PR DESCRIPTION
**Pull request by lucasgautheron**

### CODE REVIEW

**Comment by ScalaWilliam** [comment]
How about whitelisting instead of blacklisting?

Anyone who is not in (RVSF or CLA) = spectator

**Comment by lucasgautheron** [comment]
so :
 * Remove specTeams
 * Add activeTeams = Set ( "CLA", "RVSF" )

**Comment by ScalaWilliam** [comment]
Yeah.

**Comment by ScalaWilliam** [comment]
oh argh. Notice line 67. This is for DM.

**Comment by lucasgautheron** [comment]
Well DM players are attributed a team as well regardless

https://github.com/assaultcube/AC/blob/master/source/src/server.cpp#L4099

No exception is made for team or non-teammodes.
So the code in this PR should work

**Comment by ScalaWilliam** [comment]
You can use this to determine if it's a team game - 
```
!teamModes.contains(serverInfo.mode)
```
If a teamgame, None
otherwise Option(players who are in rvsf or cla)

**Comment by ScalaWilliam** [comment]
LGTM :+1:

**Pull request merged**
